services:
  db:
    image: postgres:16
    container_name: auto_db
    restart: always
    environment:
      POSTGRES_USER: automir
      POSTGRES_PASSWORD: automir
      POSTGRES_DB: automir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - next_build:/app/.next  # ← добавь это
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend:ro  # Только для чтения
      - /backend/.venv  # Отдельный том для виртуального окружения
    environment:
      - PYTHONPATH=/backend
    depends_on:
      - db
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped


volumes:
  postgres_data:
  next_build:
  minio_data: