services:
  db:
    image: postgres:16
    container_name: automir_database
    restart: always
    environment:
      POSTGRES_USER: automir
      POSTGRES_PASSWORD: automir
      POSTGRES_DB: automir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    container_name: automir_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - next_build:/app/.next  
  
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: automir_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/backend:Z

  minio:
    image: quay.io/minio/minio
    container_name: automir_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_DEFAULT_BUCKETS: "media,otherbucket"  # Убрал пробел после запятой
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  next_build:
  minio_data: