[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Mateusz",email = "matthewfootballer11@gmail.com"}
]
package-mode = false
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.115.14,<0.116.0)",
    "uvicorn[standart] (>=0.35.0,<0.36.0)",
    "black (>=25.1.0,<26.0.0)",
    "alembic (>=1.16.2,<2.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "sqlalchemy[asyncio] (>=2.0.41,<3.0.0)"
]
[tool.poetry]
package-mode = false  # Отключает режим упаковки


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
