export interface CarStats {
    name: string,
    year: number,
    gen: string,
    mileage: number,
    passport: string,
    owners_count: number,
    modification: string,
    engine_capacity: string,
    engine_type: string,
    gearbox: string,
    drive: string,
    body_type: string,
    wheel_position: string,
    status: string,
    desc: string,
}