"""updated trailer model, created car model

Revision ID: feb0c1a7ae74
Revises: 1df1442042be
Create Date: 2025-07-09 00:09:51.482188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "feb0c1a7ae74"
down_revision: Union[str, Sequence[str], None] = "1df1442042be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("engine", sa.String(length=50), nullable=False),
        sa.Column("fuel_type", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("transmission", sa.String(length=50), nullable=False),
        sa.Column("drivetrain", sa.String(length=50), nullable=False),
        sa.Column("body_type", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=50), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("owners", sa.Integer(), nullable=False),
        sa.Column("steering_wheel", sa.String(length=50), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("trim_level", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("trailers", sa.Column("axes_count", sa.Integer(), nullable=False))
    op.add_column(
        "trailers",
        sa.Column("load_capacity", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "trailers",
        sa.Column("body_volume", sa.String(length=100), nullable=False),
    )
    op.drop_column("trailers", "trailer_width")
    op.drop_column("trailers", "trailer_height")
    op.drop_column("trailers", "spring_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trailers",
        sa.Column(
            "spring_type",
            sa.VARCHAR(length=25),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "trailers",
        sa.Column(
            "trailer_height",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "trailers",
        sa.Column(
            "trailer_width",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("trailers", "body_volume")
    op.drop_column("trailers", "load_capacity")
    op.drop_column("trailers", "axes_count")
    op.drop_table("cars")
    # ### end Alembic commands ###
