"""updated models

Revision ID: a58d3d4c7415
Revises: 3daaff467fbb
Create Date: 2025-07-18 13:47:16.830790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a58d3d4c7415"
down_revision: Union[str, Sequence[str], None] = "3daaff467fbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trailers",
        sa.Column("trailer_width", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "trailers",
        sa.Column("trailer_height", sa.String(length=50), nullable=False),
    )
    op.alter_column(
        "trailers", "axes_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "trailers",
        "load_capacity",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "trailers",
        "trailer_length",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "trailers",
        "trailer_weight",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "trailers",
        "body_volume",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "trailers", "description", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trailers", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "trailers",
        "body_volume",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "trailers",
        "trailer_weight",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "trailers",
        "trailer_length",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "trailers",
        "load_capacity",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "trailers", "axes_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("trailers", "trailer_height")
    op.drop_column("trailers", "trailer_width")
    # ### end Alembic commands ###
