"""updated car

Revision ID: 249252e38865
Revises: 893f9c1edcae
Create Date: 2025-07-10 12:44:55.257922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "249252e38865"
down_revision: Union[str, Sequence[str], None] = "893f9c1edcae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars",
        "mileage",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Integer(),
        postgresql_using="mileage::integer",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars",
        "mileage",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
