"""deleted car's field drivetrain

Revision ID: 1f83db0dd3c6
Revises: 8b679d396c85
Create Date: 2025-07-23 14:53:11.870646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f83db0dd3c6"
down_revision: Union[str, Sequence[str], None] = "8b679d396c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "drivetrain")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cars",
        sa.Column(
            "drivetrain",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
