"""added product table

Revision ID: f416256d07c8
Revises: 0da6fc1ec041
Create Date: 2025-07-09 00:42:53.016318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f416256d07c8"
down_revision: Union[str, Sequence[str], None] = "0da6fc1ec041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("trailer_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trailer_id"],
            ["trailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("car_id"),
        sa.UniqueConstraint("trailer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
