"""updated trailers

Revision ID: 8b679d396c85
Revises: a58d3d4c7415
Create Date: 2025-07-18 13:49:38.570259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b679d396c85"
down_revision: Union[str, Sequence[str], None] = "a58d3d4c7415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trailers",
        "axes_count",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trailers",
        "axes_count",
        existing_type=sa.String(length=50),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
