"""added title for trailers

Revision ID: 0da6fc1ec041
Revises: feb0c1a7ae74
Create Date: 2025-07-09 00:22:39.849702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0da6fc1ec041"
down_revision: Union[str, Sequence[str], None] = "feb0c1a7ae74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trailers", sa.Column("title", sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trailers", "title")
    # ### end Alembic commands ###
