"""updated car

Revision ID: 893f9c1edcae
Revises: a5e584f3f47e
Create Date: 2025-07-10 12:41:37.910782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "893f9c1edcae"
down_revision: Union[str, Sequence[str], None] = "a5e584f3f47e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars",
        "mileage",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "cars",
        "generation",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars",
        "generation",
        existing_type=sa.String(length=50),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "cars",
        "mileage",
        existing_type=sa.String(length=50),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
