"""Trailer model

Revision ID: 1df1442042be
Revises: 05ff4eb34537
Create Date: 2025-07-07 17:02:50.126437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1df1442042be"
down_revision: Union[str, Sequence[str], None] = "05ff4eb34537"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trailers",
        sa.Column("trailer_length", sa.String(length=100), nullable=False),
        sa.Column("trailer_width", sa.String(length=100), nullable=False),
        sa.Column("trailer_height", sa.String(length=100), nullable=False),
        sa.Column("trailer_weight", sa.String(length=100), nullable=False),
        sa.Column("spring_type", sa.String(length=25), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("users", "avatar", existing_type=postgresql.BYTEA(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "avatar", existing_type=postgresql.BYTEA(), nullable=True)
    op.drop_table("trailers")
    # ### end Alembic commands ###
