"""deleted image field

Revision ID: eb9b5770756f
Revises: 1f83db0dd3c6
Create Date: 2025-07-27 17:03:52.817862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eb9b5770756f"
down_revision: Union[str, Sequence[str], None] = "1f83db0dd3c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
