"""car update

Revision ID: 3daaff467fbb
Revises: 91f55f283042
Create Date: 2025-07-12 14:49:37.349017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3daaff467fbb"
down_revision: Union[str, Sequence[str], None] = "91f55f283042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars", "engine", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "cars", "fuel_type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "cars",
        "transmission",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "cars",
        "drivetrain",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "cars", "body_type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "cars", "color", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "cars",
        "steering_wheel",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "cars",
        "generation",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "cars",
        "trim_level",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "cars", "description", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "cars",
        "trim_level",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars",
        "generation",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars",
        "steering_wheel",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars", "color", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "cars",
        "body_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars",
        "drivetrain",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars",
        "transmission",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars",
        "fuel_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "cars", "engine", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
